version: '3.9'

services:
  postgres:
    env_file:
      - .env
    container_name: postgres
    image: postgres:alpine3.18
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart:
      always 
volumes:
  pg-data: